import type { Guest } from './seating';

const roster: Guest[] = [
  {
    id: 'g1',
    name: 'Daniela Quintero',
    tableId: 't1',
    seat: 0,
    meal: 'beef',
  },
  {
    id: 'g2',
    name: 'Samuel Quintero',
    tableId: 't1',
    seat: 1,
    meal: 'beef',
  },
  {
    id: 'g3',
    name: 'Vicente Quintero',
    tableId: 't1',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g4',
    name: 'Julio Escobar',
    tableId: 't1',
    seat: 3,
    meal: 'chicken',
  },
  {
    id: 'g5',
    name: 'Marina Quintero',
    tableId: 't1',
    seat: 5,
    meal: 'beef',
  },
  {
    id: 'g6',
    name: 'Blanca Quintero',
    tableId: 't1',
    seat: 6,
    meal: 'chicken',
  },
  {
    id: 'g7',
    name: 'Maribel Marin',
    tableId: 't1',
    seat: 7,
    meal: 'chicken',
  },
  {
    id: 'g8',
    name: 'Luis Mendoza',
    tableId: 't1',
    seat: 8,
    meal: 'chicken',
  },
  {
    id: 'g9',
    name: 'Juan David Velasquez',
    tableId: 't2',
    seat: 0,
    meal: 'beef',
  },
  {
    id: 'g10',
    name: 'Francisco Valencia',
    tableId: 't2',
    seat: 1,
    meal: 'chicken',
  },
  {
    id: 'g11',
    name: 'Jessica calderon',
    tableId: 't2',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g12',
    name: 'Camila Sanchez',
    tableId: 't2',
    seat: 3,
    meal: 'chicken',
  },
  {
    id: 'g13',
    name: 'Nicolas Moreno',
    tableId: 't2',
    seat: 4,
    meal: 'beef',
  },
  {
    id: 'g14',
    name: 'Elias Nassar',
    tableId: 't2',
    seat: 5,
    meal: 'beef',
  },
  {
    id: 'g15',
    name: 'Fernanda Herrera',
    tableId: 't2',
    seat: 6,
    meal: 'chicken',
  },
  {
    id: 'g16',
    name: 'Dayana Pineda',
    tableId: 't2',
    seat: 7,
    meal: 'chicken',
  },
  {
    id: 'g17',
    name: 'Paola Ramos',
    tableId: 't2',
    seat: 8,
    meal: 'chicken',
  },
  {
    id: 'g18',
    name: 'Gabriela Villarraga',
    tableId: 't2',
    seat: 9,
    meal: 'beef',
  },
  {
    id: 'g19',
    name: 'Deibby Saenz',
    tableId: 't3',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g20',
    name: 'Daniel Saenz',
    tableId: 't3',
    seat: 3,
    meal: 'beef',
  },
  {
    id: 'g21',
    name: 'Dario Alarcon',
    tableId: 't3',
    seat: 4,
    meal: 'beef',
  },
  {
    id: 'g22',
    name: 'Nicolás',
    tableId: 't3',
    seat: 6,
    meal: null,
  },
  {
    id: 'g23',
    name: 'German Saenz',
    tableId: 't3',
    seat: 7,
    meal: 'chicken',
  },
  {
    id: 'g24',
    name: 'Marlen Murcia',
    tableId: 't3',
    seat: 8,
    meal: 'chicken',
  },
  {
    id: 'g25',
    name: 'Samuel Saenz',
    tableId: 't3',
    seat: 9,
    meal: 'beef',
  },
  {
    id: 'g26',
    name: 'Sebastian Marulanda',
    tableId: 't5',
    seat: 0,
    meal: 'beef',
  },
  {
    id: 'g27',
    name: 'Alicia Garcia',
    tableId: 't5',
    seat: 1,
    meal: 'chicken',
  },
  {
    id: 'g28',
    name: 'Sandra Garcia',
    tableId: 't5',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g29',
    name: 'Valentina Marulanda',
    tableId: 't5',
    seat: 3,
    meal: 'beef',
  },
  {
    id: 'g30',
    name: 'Luisa Fernanda',
    tableId: 't5',
    seat: 5,
    meal: 'beef',
  },
  {
    id: 'g31',
    name: 'Karen Gomez',
    tableId: 't5',
    seat: 6,
    meal: 'beef',
  },
  {
    id: 'g32',
    name: 'Cristian Arevalo',
    tableId: 't5',
    seat: 7,
    meal: 'beef',
  },
  {
    id: 'g33',
    name: 'Raul Borie',
    tableId: 't6',
    seat: 0,
    meal: 'chicken',
  },
  {
    id: 'g34',
    name: 'Liliana Cubillos',
    tableId: 't6',
    seat: 1,
    meal: 'chicken',
  },
  {
    id: 'g35',
    name: 'Sabine Borie Cubillos',
    tableId: 't6',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g36',
    name: 'Sara Cubillos',
    tableId: 't6',
    seat: 3,
    meal: 'beef',
  },
  {
    id: 'g37',
    name: 'Alejandra Cubillos',
    tableId: 't6',
    seat: 4,
    meal: 'beef',
  },
  {
    id: 'g38',
    name: 'Edilberto Cante',
    tableId: 't6',
    seat: 5,
    meal: 'beef',
  },
  {
    id: 'g39',
    name: 'Daniela Borie Cubillos',
    tableId: 't6',
    seat: 6,
    meal: 'vegetarian',
  },
  {
    id: 'g40',
    name: 'Miguel Angel Borie Cubillos',
    tableId: 't6',
    seat: 7,
    meal: 'beef',
  },
  {
    id: 'g41',
    name: 'Malú',
    tableId: 't6',
    seat: 8,
    meal: null,
  },
  {
    id: 'g42',
    name: 'Adriana Cubillos',
    tableId: 't6',
    seat: 9,
    meal: 'beef',
  },
  {
    id: 'g43',
    name: 'Lucho Rojas',
    tableId: 't7',
    seat: 0,
    meal: 'chicken',
  },
  {
    id: 'g44',
    name: 'Nubia Gordillo',
    tableId: 't7',
    seat: 1,
    meal: 'beef',
  },
  {
    id: 'g45',
    name: 'Sebastian Rojas',
    tableId: 't7',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g46',
    name: 'Santiago Rojas',
    tableId: 't7',
    seat: 3,
    meal: 'chicken',
  },
  {
    id: 'g47',
    name: 'Martin Gordillo',
    tableId: 't7',
    seat: 4,
    meal: 'beef',
  },
  {
    id: 'g48',
    name: 'Giovany Gordillo',
    tableId: 't7',
    seat: 5,
    meal: 'beef',
  },
  {
    id: 'g49',
    name: 'Diana Guzman',
    tableId: 't7',
    seat: 6,
    meal: 'beef',
  },
  {
    id: 'g50',
    name: 'Saray Gordillo',
    tableId: 't7',
    seat: 7,
    meal: 'chicken',
  },
  {
    id: 'g51',
    name: 'Pablito Gordillo',
    tableId: 't7',
    seat: 8,
    meal: 'chicken',
  },
  {
    id: 'g52',
    name: 'Dona Cecilia Gordillo',
    tableId: 't7',
    seat: 9,
    meal: 'chicken',
  },
  {
    id: 'g53',
    name: 'Javier Ortiz',
    tableId: 't8',
    seat: 0,
    meal: 'chicken',
  },
  {
    id: 'g54',
    name: 'Clarena Gómez',
    tableId: 't8',
    seat: 1,
    meal: 'chicken',
  },
  {
    id: 'g55',
    name: 'Paty Santana',
    tableId: 't8',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g56',
    name: 'Javier Tellez',
    tableId: 't8',
    seat: 3,
    meal: 'beef',
  },
  {
    id: 'g57',
    name: 'Daniela Sanchez',
    tableId: 't8',
    seat: 4,
    meal: 'chicken',
  },
  {
    id: 'g58',
    name: 'Elizabeth Ortiz',
    tableId: 't8',
    seat: 5,
    meal: 'beef',
  },
  {
    id: 'g59',
    name: 'Maria Gordillo',
    tableId: 't8',
    seat: 6,
    meal: 'chicken',
  },
  {
    id: 'g60',
    name: 'Juan David Ortiz',
    tableId: 't8',
    seat: 7,
    meal: 'beef',
  },
  {
    id: 'g61',
    name: 'Rosita Saenz',
    tableId: 't8',
    seat: 8,
    meal: 'beef',
  },
  {
    id: 'g62',
    name: 'Carmen Saenz',
    tableId: 't8',
    seat: 9,
    meal: 'chicken',
  },
  {
    id: 'g63',
    name: 'Bonifacio Saenz',
    tableId: 't9',
    seat: 0,
    meal: 'chicken',
  },
  {
    id: 'g64',
    name: 'Viviana Saenz',
    tableId: 't9',
    seat: 1,
    meal: 'beef',
  },
  {
    id: 'g65',
    name: 'Nicolas Riveros',
    tableId: 't9',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g66',
    name: 'Carolina Escandon',
    tableId: 't9',
    seat: 3,
    meal: 'chicken',
  },
  {
    id: 'g67',
    name: 'Rigoberto Saenz',
    tableId: 't9',
    seat: 4,
    meal: 'beef',
  },
  {
    id: 'g68',
    name: 'Dora Murcia',
    tableId: 't9',
    seat: 5,
    meal: 'chicken',
  },
  {
    id: 'g69',
    name: 'Jessica saenz',
    tableId: 't9',
    seat: 6,
    meal: 'beef',
  },
  {
    id: 'g70',
    name: 'Daniel Quiñones',
    tableId: 't9',
    seat: 7,
    meal: 'beef',
  },
  {
    id: 'g71',
    name: 'Marce',
    tableId: 't9',
    seat: 8,
    meal: null,
  },
  {
    id: 'g72',
    name: 'Miguel Saenz',
    tableId: 't9',
    seat: 9,
    meal: 'beef',
  },
  {
    id: 'g73',
    name: 'Jose Saenz',
    tableId: 't10',
    seat: 0,
    meal: 'beef',
  },
  {
    id: 'g74',
    name: 'Giovany Saenz',
    tableId: 't10',
    seat: 1,
    meal: 'beef',
  },
  {
    id: 'g75',
    name: 'Julanita Pérez',
    tableId: 't10',
    seat: 2,
    meal: 'beef',
  },
  {
    id: 'g76',
    name: 'Luz Dary Romero',
    tableId: 't10',
    seat: 3,
    meal: 'chicken',
  },
  {
    id: 'g77',
    name: 'Ricardo Alarcon',
    tableId: 't10',
    seat: 4,
    meal: 'beef',
  },
  {
    id: 'g78',
    name: 'Gladys Saenz',
    tableId: 't10',
    seat: 5,
    meal: 'beef',
  },
  {
    id: 'g79',
    name: 'Blanca Zapata',
    tableId: 't10',
    seat: 6,
    meal: 'beef',
  },
  {
    id: 'g80',
    name: 'Horacio Zapata',
    tableId: 't10',
    seat: 7,
    meal: 'beef',
  },
  {
    id: 'g81',
    name: 'Andrea Saenz',
    tableId: 't10',
    seat: 8,
    meal: 'beef',
  },
  {
    id: 'g82',
    name: 'Hijo',
    tableId: 't10',
    seat: 9,
    meal: null,
  },
  {
    id: 'g83',
    name: 'Mateo Espinosa Cubillos',
    tableId: 'couple',
    seat: 0,
    meal: 'chicken',
  },
  {
    id: 'g84',
    name: 'Rosa Julieth Saenz Alarcon',
    tableId: 'couple',
    seat: 1,
    meal: 'beef',
  },
  {
    id: 'g85',
    name: 'Diana Saenz',
    tableId: null,
    seat: null,
    meal: 'chicken',
  },
  {
    id: 'g86',
    name: 'Luis Ortiz',
    tableId: null,
    seat: null,
    meal: 'beef',
  },
  {
    id: 'g87',
    name: 'Santiago Alarcon',
    tableId: null,
    seat: null,
    meal: 'beef',
  },
  {
    id: 'g88',
    name: 'Jaime Ponce',
    tableId: null,
    seat: null,
    meal: 'chicken',
  },
  {
    id: 'g89',
    name: 'Ana Marcela Cubides (pareja)',
    tableId: null,
    seat: null,
    meal: 'chicken',
  },
  {
    id: 'pending-90',
    name: 'Invitado 90',
    tableId: null,
    seat: null,
    meal: null,
  },
  {
    id: 'confirmation-nicolas-tellez',
    name: 'Nicolas Tellez',
    tableId: null,
    seat: null,
    meal: 'beef',
  },
];

export default roster;
